openapi: 3.0.3
info:
  title: OCN-DNS-API API
  description: dns api server endpoints
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /api/v1/ping:
    $ref: "./path/health/api.yaml"


  /api/v1/vms/{id}/prometheus/{metricType}:
    $ref: "./path/vm/prometheus.yaml"
  /api/v1/vms/{id}/victoriametrics/{metricType}:
    $ref: "./path/vm/victoriametrics.yaml"

components:
  schemas:
    HealthResponse:
      $ref: "./schemas/HealthResponse.yaml"
    Error:
      $ref: "./schemas/Error.yaml"
    Paging:
      $ref: "./schemas/Paging.yaml"
    PagingRequest:
      $ref: "./schemas/PagingRequest.yaml"
    SearchRequest:
      $ref: "./schemas/SearchRequest.yaml"
    VMMetricType:
      $ref: "./schemas/VMMetricType.yaml"
    Monitor:
      $ref: "./schemas/Monitor.yaml"
    MonitorTarget:
      $ref: "./schemas/MonitorTarget.yaml"
    MonitorTargetData:
      $ref: "./schemas/MonitorTargetData.yaml"

  responses:
    ErrorResponse400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            bad_request:
              summary: Invalid request
              value:
                error:
                  code: 4000
                  message: "Missing required field"
    ErrorResponse401:
      description: Common error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            unauthorized:
              summary: unauthorized
              value:
                error:
                  code: 4003
                  message: "Required authentication"
            unauthorized_token_invalid:
              summary: unauthorized token invalid
              value:
                error:
                  code: 4004
                  message: "Required authentication"
            unauthorized_require_2fa:
              summary: unauthorized
              value:
                error:
                  code: 4005
                  message: "Required 2fa authentication"
            unauthorized_verify_2fa:
              summary: unauthorized
              value:
                error:
                  code: 4006
                  message: "Invalid code"
    ErrorResponse403:
      description: Common error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            forbidden:
              summary: Permission deny
              value:
                error:
                  code: 4002
                  message: "Permission deny"
    ErrorResponse404:
      description: Common error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            bad_request:
              summary: Invalid request
              value:
                error:
                  code: 4001
                  message: "Resource not found"
    ErrorResponse500:
      description: Common error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            internal_error:
              summary: internal error
              value:
                error:
                  code: 5000
                  message: "Internal connection failed"
            database_error:
              summary: database error
              value:
                error:
                  code: 5001
                  message: "Database connection failed"